variant_id: default
agent_name: backend-architect
description: Default balanced configuration for backend architecture tasks
specialization: []
model_tier: balanced
temperature: 0.7
prompt_modifications: []
performance_metrics:
  invocation_count: 1
  success_count: 1
  avg_duration: 125.3
  avg_quality_score: 0.85
  avg_reward: 2.35
  last_updated: '2025-11-20T06:20:22.046967Z'
created_at: '2025-11-19T00:00:00Z'
task_type_performance:
  security-audit:
    invocation_count: 1
    success_count: 1
    avg_duration: 125.3
    avg_quality_score: 0.85
    avg_reward: 2.35
