variant_id: default
agent_name: general-purpose
description: Default general-purpose agent for simple tasks and queries
specialization: []
model_tier: fast
temperature: 0.7
prompt_modifications: []
performance_metrics:
  invocation_count: 0
  success_count: 0
  avg_duration: 0.0
  avg_quality_score: 0.0
  avg_reward: 0.0
  last_updated: null
created_at: '2025-11-19T00:00:00Z'
task_type_performance: {}
