variant_id: default
agent_name: frontend-developer
description: Default balanced configuration for frontend development tasks
specialization: []
model_tier: balanced
temperature: 0.7
prompt_modifications: []
performance_metrics:
  invocation_count: 0
  success_count: 0
  avg_duration: 0.0
  avg_quality_score: 0.0
  avg_reward: 0.0
  last_updated: null
created_at: '2025-11-19T00:00:00Z'
task_type_performance: {}
