# A/B Test Template
# Copy this file to tests/<test_id>.yaml to configure a new A/B test

test_id: "test_001"  # Unique identifier
agent_name: "backend-architect"  # Agent being tested
status: "active"  # active, completed, cancelled

# Test Configuration
configuration:
  start_date: "2025-10-16"
  planned_duration_days: 14
  actual_end_date: null  # Filled when test completes

  # Variants
  variants:
    - id: "original"
      type: "control"
      agent_file: "agents/backend-architect.md"
      description: "Current production version"

    - id: "improved"
      type: "treatment"
      agent_file: "archive/agents/test_variants/backend-architect_v2.md"
      description: "Improved version with better error handling"

  # Traffic allocation (must sum to 1.0)
  traffic_split:
    original: 0.5
    improved: 0.5

# Hypothesis
hypothesis: |
  The improved backend-architect agent with enhanced error handling patterns
  will achieve higher success rates and better user satisfaction ratings
  compared to the original version.

# Success Criteria
success_criteria:
  primary_metric: "success_rate"
  secondary_metrics:
    - "avg_quality"
    - "avg_duration"

  # Thresholds for declaring winner
  min_improvement: 0.1  # 10% improvement required
  confidence_level: 0.95  # 95% statistical confidence
  min_sample_size: 20  # Per variant

# Data Collection
data_collection:
  # What to track
  metrics:
    - success_rate
    - failure_rate
    - avg_duration
    - avg_quality
    - user_feedback_count
    - positive_feedback_ratio

  # Exclusion criteria
  exclude_if:
    - workspace_path: "*/test-projects/*"  # Exclude test workspaces
    - duration_seconds: "> 3600"  # Exclude extremely long tasks (outliers)

# Results (filled during test)
results:
  invocation_counts:
    original: 0
    improved: 0

  metrics:
    original:
      success_rate: null
      avg_quality: null
      avg_duration: null
      user_satisfaction: null

    improved:
      success_rate: null
      avg_quality: null
      avg_duration: null
      user_satisfaction: null

  # Statistical analysis
  statistical_analysis:
    primary_metric_p_value: null
    confidence_interval: null
    effect_size: null
    winner: null  # original, improved, inconclusive

# Decision
decision:
  outcome: null  # promote, rollback, extend_test, redesign
  decided_by: null  # human, automatic
  decided_date: null
  reasoning: null

# Notes
notes: |
  Additional context or observations during the test.
  Update this as the test progresses.
