# Phase 5: Agent Curation Configuration
# Controls automatic agent improvement and A/B testing

version: "1.0"

# Failure Analysis Thresholds
failure_detection:
  min_invocations: 10  # Minimum invocations before considering agent for review
  failure_rate_threshold: 0.3  # 30% failure rate triggers analysis
  low_quality_threshold: 2.5  # Average quality < 2.5 triggers review

# Improvement Criteria
improvement_triggers:
  # When to propose agent improvements
  consistent_failures: 5  # N consecutive failures
  user_feedback_negative: 3  # N negative feedback instances
  duration_excessive: true  # Duration > 2x median for agent type
  quality_declining: true  # Quality trend declining over time

# A/B Testing Configuration
ab_testing:
  enabled: true
  sample_size: 20  # Minimum invocations per variant
  confidence_level: 0.95  # Statistical significance threshold
  max_concurrent_tests: 3  # Max parallel A/B tests
  test_duration_days: 14  # Default test duration

  # Metrics to track
  metrics:
    - success_rate
    - avg_duration
    - avg_quality
    - user_satisfaction

# Curation Decision Framework
decision_criteria:
  # Automatic decisions
  auto_promote:
    min_success_rate: 0.85
    min_quality: 4.0
    min_sample_size: 20

  auto_rollback:
    max_failure_rate: 0.5
    min_quality: 2.0

  # Manual review required
  manual_review:
    ambiguous_results: true  # Stats don't show clear winner
    mixed_feedback: true  # Some metrics improved, others declined
    insufficient_data: true  # Sample size < threshold

# Agent Improvement Workflow
improvement_workflow:
  phases:
    - name: "Failure Analysis"
      automatic: true
      output: "reports/failures/agent_<name>_<date>.json"

    - name: "Improvement Proposal"
      automatic: true
      output: "reports/improvements/agent_<name>_proposal_<date>.md"

    - name: "Manual Review"
      automatic: false
      required_approval: true

    - name: "A/B Test Setup"
      automatic: true
      creates_variant: true

    - name: "Data Collection"
      automatic: true
      duration_days: 14

    - name: "Statistical Analysis"
      automatic: true
      output: "reports/ab_tests/test_<id>_results_<date>.json"

    - name: "Curation Decision"
      automatic: false  # Manual decision required
      options: ["promote", "rollback", "extend_test", "redesign"]

    - name: "Apply Changes"
      automatic: true
      updates_agent: true

# Archive and Backup
archive:
  original_agents_dir: "archive/agents/originals"
  improved_agents_dir: "archive/agents/improved"
  test_variants_dir: "archive/agents/test_variants"
  retention_days: 365

# Notification Settings
notifications:
  slack_webhook: null  # Optional Slack integration
  email_recipients: []  # Optional email notifications
  notify_on:
    - test_complete
    - auto_decision_blocked
    - manual_review_required
